spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hadoop
    url: jdbc:mysql://127.0.0.1:3306/zhuriPlan?useSSL=false
  application:
    name: PlanManagement-Facade
  servlet:
    multipart:
      # 针对post请求数据量可能过大的情况
      maxFileSize: 100
      maxRequestSize: 100
mybatis:
  type-handlers-package: org.plan.managementfacade.model.planModel.sqlModel
