spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hadoop
    url: jdbc:mysql://127.0.0.1:3306/zhuriPlan?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  application:
    name: PlanManagement-Web
  servlet:
    multipart:
      # 针对post请求数据量可能过大的情况
      maxFileSize: 100
      maxRequestSize: 100
  output:
    ansi:
      enabled: detect

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:org/plan/managementservice/mapper/**/*Mapper.xml

logging:
  level:
    org.material.managementservice.mapper.*: trace
