spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/zhuriPlan?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  application:
    name: PlanService
  servlet:
    multipart:
      # 针对post请求数据量可能过大的情况
      maxFileSize: 100MB
      maxRequestSize: 100MB
  output:
    ansi:
      enabled: detect
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:org/plan/managementservice/mapper/**/*Mapper.xml
  type-handlers-package: org.plan.managementfacade.model.enumModel, org.plan.managementfacade.model.planModel.sqlModel

logging:
  level:
    org.plan.managementservice.mapper.*: trace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

security:
  oauth2:
    resource:
      jwt:
        key-value: 123
      id: openid

# 存储文件的文件夹路径
plan:
  file:
    dir: /home/malous/Postman/